name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

jobs:
  devsecops-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Gitleaks - Secrets Scan
      - name: Run Gitleaks Secret Scan
        uses: zricethezav/gitleaks-action@v2.3.2
        with:
          config-path: .gitleaks.toml
        continue-on-error: true

      # 2. OWASP Dependency-Check - Vulnerability Scan
      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "devsecops-project"
          format: "HTML"
          out: "reports"
        continue-on-error: true

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html

      # 3. SonarCloud - Code Quality and SAST
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .

  container-scan:
    name: Trivy Container Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Trivy vulnerability scan
        run: trivy image --severity HIGH,CRITICAL --no-progress --format table -o trivy-report.txt myapp:latest

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.txt
