name: Hello World DevSecOps

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "GitHub Actions works! 🚀"

      # OPTIONAL: Install dependencies (use only if you have package.json)
      # - name: Install Dependencies
      #   run: npm install

      - name: SAST with SonarCloud (Updated)
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
